In [0]:
import numpy as np
import pandas as pd
import tensorflow as tf

In [2]:
tf.__version__

'2.2.0'

In [0]:
dataset = pd.read_csv('Churn_Modelling.csv')
X = dataset.iloc[:, 3:-1].values
y = dataset.iloc[:, -1].values

In [4]:
print(X)

[[619 'France' 'Female' ... 1 1 101348.88]
 [608 'Spain' 'Female' ... 0 1 112542.58]
 [502 'France' 'Female' ... 1 0 113931.57]
 ...
 [709 'France' 'Female' ... 0 1 42085.58]
 [772 'Germany' 'Male' ... 1 0 92888.52]
 [792 'France' 'Female' ... 1 0 38190.78]]


In [5]:
print(y)

[1 0 1 ... 1 1 0]


In [0]:
from sklearn.preprocessing import LabelEncoder
le = LabelEncoder()
X[:, 2] = le.fit_transform(X[:, 2])

In [7]:
print(X)

[[619 'France' 0 ... 1 1 101348.88]
 [608 'Spain' 0 ... 0 1 112542.58]
 [502 'France' 0 ... 1 0 113931.57]
 ...
 [709 'France' 0 ... 0 1 42085.58]
 [772 'Germany' 1 ... 1 0 92888.52]
 [792 'France' 0 ... 1 0 38190.78]]


In [0]:
from sklearn.compose import ColumnTransformer
from sklearn.preprocessing import OneHotEncoder
ct = ColumnTransformer(transformers=[('encoder', OneHotEncoder(), [1])], remainder='passthrough')
X = np.array(ct.fit_transform(X))

In [9]:
print(X)

[[1.0 0.0 0.0 ... 1 1 101348.88]
 [0.0 0.0 1.0 ... 0 1 112542.58]
 [1.0 0.0 0.0 ... 1 0 113931.57]
 ...
 [1.0 0.0 0.0 ... 0 1 42085.58]
 [0.0 1.0 0.0 ... 1 0 92888.52]
 [1.0 0.0 0.0 ... 1 0 38190.78]]


In [0]:
from sklearn.preprocessing import StandardScaler
sc = StandardScaler()
X = sc.fit_transform(X)

In [11]:
print(X)

[[ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167  0.97024255
   0.02188649]
 [-1.00280393 -0.57873591  1.74273971 ... -1.54776799  0.97024255
   0.21653375]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.2406869 ]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ... -1.54776799  0.97024255
  -1.00864308]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
  -0.12523071]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
  -1.07636976]]


In [0]:
from sklearn.model_selection import train_test_split
X_train, X_test, y_train, y_test = train_test_split(X, y, test_size = 0.2, random_state = 0)

In [13]:
print(X_train)

[[-1.00280393 -0.57873591  1.74273971 ...  0.64609167 -1.03067011
   1.10838187]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167  0.97024255
  -0.74759209]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   1.48746417]
 ...
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   1.41441489]
 [-1.00280393 -0.57873591  1.74273971 ...  0.64609167  0.97024255
   0.84614739]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
   0.32630495]]


In [14]:
print(X_test)

[[-1.00280393  1.72790383 -0.57380915 ...  0.64609167  0.97024255
   1.61304597]
 [ 0.99720391 -0.57873591 -0.57380915 ...  0.64609167 -1.03067011
   0.49753166]
 [-1.00280393 -0.57873591  1.74273971 ...  0.64609167  0.97024255
  -0.4235611 ]
 ...
 [-1.00280393 -0.57873591  1.74273971 ...  0.64609167 -1.03067011
   0.72065149]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167  0.97024255
  -1.54438254]
 [-1.00280393  1.72790383 -0.57380915 ...  0.64609167 -1.03067011
   1.61474887]]


In [0]:
#Initialising the ANN
ann = tf.keras.models.Sequential()

In [0]:
#Add input layer and first hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [0]:
#Add second hidden layer
ann.add(tf.keras.layers.Dense(units=6, activation='relu'))

In [0]:
#Add output layer
ann.add(tf.keras.layers.Dense(units=1, activation='sigmoid'))

In [0]:
ann.compile(optimizer = 'adam', loss = 'binary_crossentropy', metrics = ['accuracy'])
ann.fit(X_train, y_train, batch_size = 32, epochs = 100)

In [20]:
#Prediction
y_pred = ann.predict(X_test)
y_pred = (y_pred > 0.5)
print(np.concatenate((y_pred.reshape(len(y_pred),1), y_test.reshape(len(y_test),1)),1))

[[0 0]
 [0 1]
 [0 0]
 ...
 [0 0]
 [0 0]
 [0 0]]


In [21]:
from sklearn.metrics import confusion_matrix
cm = confusion_matrix(y_test, y_pred)
print(cm)

[[1517   78]
 [ 198  207]]
